# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ibc/applications/interchain_accounts/v1/account.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cosmos_proto import cosmos_pb2 as cosmos__proto_dot_cosmos__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from cosmos.auth.v1beta1 import auth_pb2 as cosmos_dot_auth_dot_v1beta1_dot_auth__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ibc/applications/interchain_accounts/v1/account.proto',
  package='ibc.applications.interchain_accounts.v1',
  syntax='proto3',
  serialized_options=_b('ZEgithub.com/cosmos/ibc-go/v7/modules/apps/27-interchain-accounts/types'),
  serialized_pb=_b('\n5ibc/applications/interchain_accounts/v1/account.proto\x12\'ibc.applications.interchain_accounts.v1\x1a\x19\x63osmos_proto/cosmos.proto\x1a\x14gogoproto/gogo.proto\x1a\x1e\x63osmos/auth/v1beta1/auth.proto\"\xcb\x01\n\x11InterchainAccount\x12I\n\x0c\x62\x61se_account\x18\x01 \x01(\x0b\x32 .cosmos.auth.v1beta1.BaseAccountB\x04\xd0\xde\x1f\x01R\x0b\x62\x61seAccount\x12#\n\raccount_owner\x18\x02 \x01(\tR\x0c\x61\x63\x63ountOwner:F\x88\xa0\x1f\x00\x98\xa0\x1f\x00\xca\xb4-:ibc.applications.interchain_accounts.v1.InterchainAccountIBGZEgithub.com/cosmos/ibc-go/v7/modules/apps/27-interchain-accounts/typesb\x06proto3')
  ,
  dependencies=[cosmos__proto_dot_cosmos__pb2.DESCRIPTOR,gogoproto_dot_gogo__pb2.DESCRIPTOR,cosmos_dot_auth_dot_v1beta1_dot_auth__pb2.DESCRIPTOR,])




_INTERCHAINACCOUNT = _descriptor.Descriptor(
  name='InterchainAccount',
  full_name='ibc.applications.interchain_accounts.v1.InterchainAccount',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='base_account', full_name='ibc.applications.interchain_accounts.v1.InterchainAccount.base_account', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\320\336\037\001'), json_name='baseAccount', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='account_owner', full_name='ibc.applications.interchain_accounts.v1.InterchainAccount.account_owner', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='accountOwner', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('\210\240\037\000\230\240\037\000\312\264-:ibc.applications.interchain_accounts.v1.InterchainAccountI'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=180,
  serialized_end=383,
)

_INTERCHAINACCOUNT.fields_by_name['base_account'].message_type = cosmos_dot_auth_dot_v1beta1_dot_auth__pb2._BASEACCOUNT
DESCRIPTOR.message_types_by_name['InterchainAccount'] = _INTERCHAINACCOUNT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InterchainAccount = _reflection.GeneratedProtocolMessageType('InterchainAccount', (_message.Message,), dict(
  DESCRIPTOR = _INTERCHAINACCOUNT,
  __module__ = 'ibc.applications.interchain_accounts.v1.account_pb2'
  # @@protoc_insertion_point(class_scope:ibc.applications.interchain_accounts.v1.InterchainAccount)
  ))
_sym_db.RegisterMessage(InterchainAccount)


DESCRIPTOR._options = None
_INTERCHAINACCOUNT.fields_by_name['base_account']._options = None
_INTERCHAINACCOUNT._options = None
# @@protoc_insertion_point(module_scope)
