# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/evidence/v1beta1/query.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cosmos.base.query.v1beta1 import pagination_pb2 as cosmos_dot_base_dot_query_dot_v1beta1_dot_pagination__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cosmos/evidence/v1beta1/query.proto',
  package='cosmos.evidence.v1beta1',
  syntax='proto3',
  serialized_options=_b('Z\035cosmossdk.io/x/evidence/types'),
  serialized_pb=_b('\n#cosmos/evidence/v1beta1/query.proto\x12\x17\x63osmos.evidence.v1beta1\x1a*cosmos/base/query/v1beta1/pagination.proto\x1a\x19google/protobuf/any.proto\x1a\x1cgoogle/api/annotations.proto\"S\n\x14QueryEvidenceRequest\x12\'\n\revidence_hash\x18\x01 \x01(\x0c\x42\x02\x18\x01R\x0c\x65videnceHash\x12\x12\n\x04hash\x18\x02 \x01(\tR\x04hash\"I\n\x15QueryEvidenceResponse\x12\x30\n\x08\x65vidence\x18\x01 \x01(\x0b\x32\x14.google.protobuf.AnyR\x08\x65vidence\"a\n\x17QueryAllEvidenceRequest\x12\x46\n\npagination\x18\x01 \x01(\x0b\x32&.cosmos.base.query.v1beta1.PageRequestR\npagination\"\x95\x01\n\x18QueryAllEvidenceResponse\x12\x30\n\x08\x65vidence\x18\x01 \x03(\x0b\x32\x14.google.protobuf.AnyR\x08\x65vidence\x12G\n\npagination\x18\x02 \x01(\x0b\x32\'.cosmos.base.query.v1beta1.PageResponseR\npagination2\xc5\x02\n\x05Query\x12\x9b\x01\n\x08\x45vidence\x12-.cosmos.evidence.v1beta1.QueryEvidenceRequest\x1a..cosmos.evidence.v1beta1.QueryEvidenceResponse\"0\x82\xd3\xe4\x93\x02*\x12(/cosmos/evidence/v1beta1/evidence/{hash}\x12\x9d\x01\n\x0b\x41llEvidence\x12\x30.cosmos.evidence.v1beta1.QueryAllEvidenceRequest\x1a\x31.cosmos.evidence.v1beta1.QueryAllEvidenceResponse\")\x82\xd3\xe4\x93\x02#\x12!/cosmos/evidence/v1beta1/evidenceB\x1fZ\x1d\x63osmossdk.io/x/evidence/typesb\x06proto3')
  ,
  dependencies=[cosmos_dot_base_dot_query_dot_v1beta1_dot_pagination__pb2.DESCRIPTOR,google_dot_protobuf_dot_any__pb2.DESCRIPTOR,google_dot_api_dot_annotations__pb2.DESCRIPTOR,])




_QUERYEVIDENCEREQUEST = _descriptor.Descriptor(
  name='QueryEvidenceRequest',
  full_name='cosmos.evidence.v1beta1.QueryEvidenceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='evidence_hash', full_name='cosmos.evidence.v1beta1.QueryEvidenceRequest.evidence_hash', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\030\001'), json_name='evidenceHash', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hash', full_name='cosmos.evidence.v1beta1.QueryEvidenceRequest.hash', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='hash', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=248,
)


_QUERYEVIDENCERESPONSE = _descriptor.Descriptor(
  name='QueryEvidenceResponse',
  full_name='cosmos.evidence.v1beta1.QueryEvidenceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='evidence', full_name='cosmos.evidence.v1beta1.QueryEvidenceResponse.evidence', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='evidence', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=250,
  serialized_end=323,
)


_QUERYALLEVIDENCEREQUEST = _descriptor.Descriptor(
  name='QueryAllEvidenceRequest',
  full_name='cosmos.evidence.v1beta1.QueryAllEvidenceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pagination', full_name='cosmos.evidence.v1beta1.QueryAllEvidenceRequest.pagination', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='pagination', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=325,
  serialized_end=422,
)


_QUERYALLEVIDENCERESPONSE = _descriptor.Descriptor(
  name='QueryAllEvidenceResponse',
  full_name='cosmos.evidence.v1beta1.QueryAllEvidenceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='evidence', full_name='cosmos.evidence.v1beta1.QueryAllEvidenceResponse.evidence', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='evidence', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pagination', full_name='cosmos.evidence.v1beta1.QueryAllEvidenceResponse.pagination', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='pagination', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=425,
  serialized_end=574,
)

_QUERYEVIDENCERESPONSE.fields_by_name['evidence'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_QUERYALLEVIDENCEREQUEST.fields_by_name['pagination'].message_type = cosmos_dot_base_dot_query_dot_v1beta1_dot_pagination__pb2._PAGEREQUEST
_QUERYALLEVIDENCERESPONSE.fields_by_name['evidence'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_QUERYALLEVIDENCERESPONSE.fields_by_name['pagination'].message_type = cosmos_dot_base_dot_query_dot_v1beta1_dot_pagination__pb2._PAGERESPONSE
DESCRIPTOR.message_types_by_name['QueryEvidenceRequest'] = _QUERYEVIDENCEREQUEST
DESCRIPTOR.message_types_by_name['QueryEvidenceResponse'] = _QUERYEVIDENCERESPONSE
DESCRIPTOR.message_types_by_name['QueryAllEvidenceRequest'] = _QUERYALLEVIDENCEREQUEST
DESCRIPTOR.message_types_by_name['QueryAllEvidenceResponse'] = _QUERYALLEVIDENCERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

QueryEvidenceRequest = _reflection.GeneratedProtocolMessageType('QueryEvidenceRequest', (_message.Message,), dict(
  DESCRIPTOR = _QUERYEVIDENCEREQUEST,
  __module__ = 'cosmos.evidence.v1beta1.query_pb2'
  # @@protoc_insertion_point(class_scope:cosmos.evidence.v1beta1.QueryEvidenceRequest)
  ))
_sym_db.RegisterMessage(QueryEvidenceRequest)

QueryEvidenceResponse = _reflection.GeneratedProtocolMessageType('QueryEvidenceResponse', (_message.Message,), dict(
  DESCRIPTOR = _QUERYEVIDENCERESPONSE,
  __module__ = 'cosmos.evidence.v1beta1.query_pb2'
  # @@protoc_insertion_point(class_scope:cosmos.evidence.v1beta1.QueryEvidenceResponse)
  ))
_sym_db.RegisterMessage(QueryEvidenceResponse)

QueryAllEvidenceRequest = _reflection.GeneratedProtocolMessageType('QueryAllEvidenceRequest', (_message.Message,), dict(
  DESCRIPTOR = _QUERYALLEVIDENCEREQUEST,
  __module__ = 'cosmos.evidence.v1beta1.query_pb2'
  # @@protoc_insertion_point(class_scope:cosmos.evidence.v1beta1.QueryAllEvidenceRequest)
  ))
_sym_db.RegisterMessage(QueryAllEvidenceRequest)

QueryAllEvidenceResponse = _reflection.GeneratedProtocolMessageType('QueryAllEvidenceResponse', (_message.Message,), dict(
  DESCRIPTOR = _QUERYALLEVIDENCERESPONSE,
  __module__ = 'cosmos.evidence.v1beta1.query_pb2'
  # @@protoc_insertion_point(class_scope:cosmos.evidence.v1beta1.QueryAllEvidenceResponse)
  ))
_sym_db.RegisterMessage(QueryAllEvidenceResponse)


DESCRIPTOR._options = None
_QUERYEVIDENCEREQUEST.fields_by_name['evidence_hash']._options = None

_QUERY = _descriptor.ServiceDescriptor(
  name='Query',
  full_name='cosmos.evidence.v1beta1.Query',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=577,
  serialized_end=902,
  methods=[
  _descriptor.MethodDescriptor(
    name='Evidence',
    full_name='cosmos.evidence.v1beta1.Query.Evidence',
    index=0,
    containing_service=None,
    input_type=_QUERYEVIDENCEREQUEST,
    output_type=_QUERYEVIDENCERESPONSE,
    serialized_options=_b('\202\323\344\223\002*\022(/cosmos/evidence/v1beta1/evidence/{hash}'),
  ),
  _descriptor.MethodDescriptor(
    name='AllEvidence',
    full_name='cosmos.evidence.v1beta1.Query.AllEvidence',
    index=1,
    containing_service=None,
    input_type=_QUERYALLEVIDENCEREQUEST,
    output_type=_QUERYALLEVIDENCERESPONSE,
    serialized_options=_b('\202\323\344\223\002#\022!/cosmos/evidence/v1beta1/evidence'),
  ),
])
_sym_db.RegisterServiceDescriptor(_QUERY)

DESCRIPTOR.services_by_name['Query'] = _QUERY

# @@protoc_insertion_point(module_scope)
