# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: osmosis/epochs/query.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from cosmos.base.query.v1beta1 import pagination_pb2 as cosmos_dot_base_dot_query_dot_v1beta1_dot_pagination__pb2
from osmosis.epochs import genesis_pb2 as osmosis_dot_epochs_dot_genesis__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='osmosis/epochs/query.proto',
  package='osmosis.epochs.v1beta1',
  syntax='proto3',
  serialized_options=_b('Z2github.com/osmosis-labs/osmosis/v12/x/epochs/types'),
  serialized_pb=_b('\n\x1aosmosis/epochs/query.proto\x12\x16osmosis.epochs.v1beta1\x1a\x14gogoproto/gogo.proto\x1a\x1cgoogle/api/annotations.proto\x1a*cosmos/base/query/v1beta1/pagination.proto\x1a\x1cosmosis/epochs/genesis.proto\"\x18\n\x16QueryEpochsInfoRequest\"Z\n\x17QueryEpochsInfoResponse\x12?\n\x06\x65pochs\x18\x01 \x03(\x0b\x32!.osmosis.epochs.v1beta1.EpochInfoB\x04\xc8\xde\x1f\x00R\x06\x65pochs\":\n\x18QueryCurrentEpochRequest\x12\x1e\n\nidentifier\x18\x01 \x01(\tR\nidentifier\"@\n\x19QueryCurrentEpochResponse\x12#\n\rcurrent_epoch\x18\x01 \x01(\x03R\x0c\x63urrentEpoch2\xc4\x02\n\x05Query\x12\x95\x01\n\nEpochInfos\x12..osmosis.epochs.v1beta1.QueryEpochsInfoRequest\x1a/.osmosis.epochs.v1beta1.QueryEpochsInfoResponse\"&\x82\xd3\xe4\x93\x02 \x12\x1e/osmosis/epochs/v1beta1/epochs\x12\xa2\x01\n\x0c\x43urrentEpoch\x12\x30.osmosis.epochs.v1beta1.QueryCurrentEpochRequest\x1a\x31.osmosis.epochs.v1beta1.QueryCurrentEpochResponse\"-\x82\xd3\xe4\x93\x02\'\x12%/osmosis/epochs/v1beta1/current_epochB4Z2github.com/osmosis-labs/osmosis/v12/x/epochs/typesb\x06proto3')
  ,
  dependencies=[gogoproto_dot_gogo__pb2.DESCRIPTOR,google_dot_api_dot_annotations__pb2.DESCRIPTOR,cosmos_dot_base_dot_query_dot_v1beta1_dot_pagination__pb2.DESCRIPTOR,osmosis_dot_epochs_dot_genesis__pb2.DESCRIPTOR,])




_QUERYEPOCHSINFOREQUEST = _descriptor.Descriptor(
  name='QueryEpochsInfoRequest',
  full_name='osmosis.epochs.v1beta1.QueryEpochsInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=180,
  serialized_end=204,
)


_QUERYEPOCHSINFORESPONSE = _descriptor.Descriptor(
  name='QueryEpochsInfoResponse',
  full_name='osmosis.epochs.v1beta1.QueryEpochsInfoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='epochs', full_name='osmosis.epochs.v1beta1.QueryEpochsInfoResponse.epochs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\310\336\037\000'), json_name='epochs', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=206,
  serialized_end=296,
)


_QUERYCURRENTEPOCHREQUEST = _descriptor.Descriptor(
  name='QueryCurrentEpochRequest',
  full_name='osmosis.epochs.v1beta1.QueryCurrentEpochRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='identifier', full_name='osmosis.epochs.v1beta1.QueryCurrentEpochRequest.identifier', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='identifier', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=298,
  serialized_end=356,
)


_QUERYCURRENTEPOCHRESPONSE = _descriptor.Descriptor(
  name='QueryCurrentEpochResponse',
  full_name='osmosis.epochs.v1beta1.QueryCurrentEpochResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='current_epoch', full_name='osmosis.epochs.v1beta1.QueryCurrentEpochResponse.current_epoch', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='currentEpoch', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=358,
  serialized_end=422,
)

_QUERYEPOCHSINFORESPONSE.fields_by_name['epochs'].message_type = osmosis_dot_epochs_dot_genesis__pb2._EPOCHINFO
DESCRIPTOR.message_types_by_name['QueryEpochsInfoRequest'] = _QUERYEPOCHSINFOREQUEST
DESCRIPTOR.message_types_by_name['QueryEpochsInfoResponse'] = _QUERYEPOCHSINFORESPONSE
DESCRIPTOR.message_types_by_name['QueryCurrentEpochRequest'] = _QUERYCURRENTEPOCHREQUEST
DESCRIPTOR.message_types_by_name['QueryCurrentEpochResponse'] = _QUERYCURRENTEPOCHRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

QueryEpochsInfoRequest = _reflection.GeneratedProtocolMessageType('QueryEpochsInfoRequest', (_message.Message,), dict(
  DESCRIPTOR = _QUERYEPOCHSINFOREQUEST,
  __module__ = 'osmosis.epochs.query_pb2'
  # @@protoc_insertion_point(class_scope:osmosis.epochs.v1beta1.QueryEpochsInfoRequest)
  ))
_sym_db.RegisterMessage(QueryEpochsInfoRequest)

QueryEpochsInfoResponse = _reflection.GeneratedProtocolMessageType('QueryEpochsInfoResponse', (_message.Message,), dict(
  DESCRIPTOR = _QUERYEPOCHSINFORESPONSE,
  __module__ = 'osmosis.epochs.query_pb2'
  # @@protoc_insertion_point(class_scope:osmosis.epochs.v1beta1.QueryEpochsInfoResponse)
  ))
_sym_db.RegisterMessage(QueryEpochsInfoResponse)

QueryCurrentEpochRequest = _reflection.GeneratedProtocolMessageType('QueryCurrentEpochRequest', (_message.Message,), dict(
  DESCRIPTOR = _QUERYCURRENTEPOCHREQUEST,
  __module__ = 'osmosis.epochs.query_pb2'
  # @@protoc_insertion_point(class_scope:osmosis.epochs.v1beta1.QueryCurrentEpochRequest)
  ))
_sym_db.RegisterMessage(QueryCurrentEpochRequest)

QueryCurrentEpochResponse = _reflection.GeneratedProtocolMessageType('QueryCurrentEpochResponse', (_message.Message,), dict(
  DESCRIPTOR = _QUERYCURRENTEPOCHRESPONSE,
  __module__ = 'osmosis.epochs.query_pb2'
  # @@protoc_insertion_point(class_scope:osmosis.epochs.v1beta1.QueryCurrentEpochResponse)
  ))
_sym_db.RegisterMessage(QueryCurrentEpochResponse)


DESCRIPTOR._options = None
_QUERYEPOCHSINFORESPONSE.fields_by_name['epochs']._options = None

_QUERY = _descriptor.ServiceDescriptor(
  name='Query',
  full_name='osmosis.epochs.v1beta1.Query',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=425,
  serialized_end=749,
  methods=[
  _descriptor.MethodDescriptor(
    name='EpochInfos',
    full_name='osmosis.epochs.v1beta1.Query.EpochInfos',
    index=0,
    containing_service=None,
    input_type=_QUERYEPOCHSINFOREQUEST,
    output_type=_QUERYEPOCHSINFORESPONSE,
    serialized_options=_b('\202\323\344\223\002 \022\036/osmosis/epochs/v1beta1/epochs'),
  ),
  _descriptor.MethodDescriptor(
    name='CurrentEpoch',
    full_name='osmosis.epochs.v1beta1.Query.CurrentEpoch',
    index=1,
    containing_service=None,
    input_type=_QUERYCURRENTEPOCHREQUEST,
    output_type=_QUERYCURRENTEPOCHRESPONSE,
    serialized_options=_b('\202\323\344\223\002\'\022%/osmosis/epochs/v1beta1/current_epoch'),
  ),
])
_sym_db.RegisterServiceDescriptor(_QUERY)

DESCRIPTOR.services_by_name['Query'] = _QUERY

# @@protoc_insertion_point(module_scope)
