version: "3.9"

services: 
  pypy:
    build: ./pypy
    image: ${REGISTRY-registry.gitlab.com/dysonproject}/dyson/pypy:3.9

  chain:
    build: 
      context: ./chain
      args:
        - TAG=${TAG}
    image: ${REGISTRY-registry.gitlab.com/dysonproject}/dyson/chain:${TAG}
    command: make start
    environment:
      - TAG
    env_file:
      - .env 
    ports: 
      - "26656-26657:26656-26657"
      - "1317:1317"
    volumes:
      - ./chain_home:/root/
      - ./chain:/go/src/app

  frontend:
    build: ./frontend
    image: ${REGISTRY-registry.gitlab.com/dysonproject}/dyson/frontend:${TAG}
    command: make dev
    env_file:
      - .env 
    volumes:
      - ./frontend:/code
      - ./frontend_home:/root/
    ports:
      - "${PORT-8000}:8000"
      - "8001:8001"
      - "80:80"
    environment:
      - DYSON_RESTHOST=http://chain:1317
      - CLEAR_DOMAIN=$CLEAR_DOMAIN
      - TAG
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

  vue:
    build: ./chain/vue
    image: ${REGISTRY-registry.gitlab.com/dysonproject}/dyson/vue:${TAG}
    command: "make dev"
    user: "${UID-1000}:${GID-1000}"
    env_file:
      - .env 
    ports:
      - "3000:3000"
    volumes:
      - ./chain/vue:/app
      - ./frontend/vue:/app/dist/
      - ./frontend_home:/root/

