# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/slashing/v1beta1/tx.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from cosmos.slashing.v1beta1 import slashing_pb2 as cosmos_dot_slashing_dot_v1beta1_dot_slashing__pb2
from cosmos_proto import cosmos_pb2 as cosmos__proto_dot_cosmos__pb2
from cosmos.msg.v1 import msg_pb2 as cosmos_dot_msg_dot_v1_dot_msg__pb2
from amino import amino_pb2 as amino_dot_amino__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cosmos/slashing/v1beta1/tx.proto',
  package='cosmos.slashing.v1beta1',
  syntax='proto3',
  serialized_options=_b('Z-github.com/cosmos/cosmos-sdk/x/slashing/types\250\342\036\001'),
  serialized_pb=_b('\n cosmos/slashing/v1beta1/tx.proto\x12\x17\x63osmos.slashing.v1beta1\x1a\x14gogoproto/gogo.proto\x1a&cosmos/slashing/v1beta1/slashing.proto\x1a\x19\x63osmos_proto/cosmos.proto\x1a\x17\x63osmos/msg/v1/msg.proto\x1a\x11\x61mino/amino.proto\"\xa3\x01\n\tMsgUnjail\x12\x64\n\x0evalidator_addr\x18\x01 \x01(\tB=\xea\xde\x1f\x07\x61\x64\x64ress\xd2\xb4-\x1d\x63osmos.ValidatorAddressString\xa2\xe7\xb0*\x07\x61\x64\x64ress\xa8\xe7\xb0*\x01R\rvalidatorAddr:0\x88\xa0\x1f\x00\x82\xe7\xb0*\x0evalidator_addr\x8a\xe7\xb0*\x14\x63osmos-sdk/MsgUnjail\"\x13\n\x11MsgUnjailResponse\"\xc7\x01\n\x0fMsgUpdateParams\x12\x36\n\tauthority\x18\x01 \x01(\tB\x18\xd2\xb4-\x14\x63osmos.AddressStringR\tauthority\x12\x42\n\x06params\x18\x02 \x01(\x0b\x32\x1f.cosmos.slashing.v1beta1.ParamsB\t\xc8\xde\x1f\x00\xa8\xe7\xb0*\x01R\x06params:8\x82\xe7\xb0*\tauthority\x8a\xe7\xb0*%cosmos-sdk/x/slashing/MsgUpdateParams\"\x19\n\x17MsgUpdateParamsResponse2\xd2\x01\n\x03Msg\x12X\n\x06Unjail\x12\".cosmos.slashing.v1beta1.MsgUnjail\x1a*.cosmos.slashing.v1beta1.MsgUnjailResponse\x12j\n\x0cUpdateParams\x12(.cosmos.slashing.v1beta1.MsgUpdateParams\x1a\x30.cosmos.slashing.v1beta1.MsgUpdateParamsResponse\x1a\x05\x80\xe7\xb0*\x01\x42\x33Z-github.com/cosmos/cosmos-sdk/x/slashing/types\xa8\xe2\x1e\x01\x62\x06proto3')
  ,
  dependencies=[gogoproto_dot_gogo__pb2.DESCRIPTOR,cosmos_dot_slashing_dot_v1beta1_dot_slashing__pb2.DESCRIPTOR,cosmos__proto_dot_cosmos__pb2.DESCRIPTOR,cosmos_dot_msg_dot_v1_dot_msg__pb2.DESCRIPTOR,amino_dot_amino__pb2.DESCRIPTOR,])




_MSGUNJAIL = _descriptor.Descriptor(
  name='MsgUnjail',
  full_name='cosmos.slashing.v1beta1.MsgUnjail',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='validator_addr', full_name='cosmos.slashing.v1beta1.MsgUnjail.validator_addr', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\352\336\037\007address\322\264-\035cosmos.ValidatorAddressString\242\347\260*\007address\250\347\260*\001'), json_name='validatorAddr', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('\210\240\037\000\202\347\260*\016validator_addr\212\347\260*\024cosmos-sdk/MsgUnjail'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=195,
  serialized_end=358,
)


_MSGUNJAILRESPONSE = _descriptor.Descriptor(
  name='MsgUnjailResponse',
  full_name='cosmos.slashing.v1beta1.MsgUnjailResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=360,
  serialized_end=379,
)


_MSGUPDATEPARAMS = _descriptor.Descriptor(
  name='MsgUpdateParams',
  full_name='cosmos.slashing.v1beta1.MsgUpdateParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='authority', full_name='cosmos.slashing.v1beta1.MsgUpdateParams.authority', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\322\264-\024cosmos.AddressString'), json_name='authority', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='params', full_name='cosmos.slashing.v1beta1.MsgUpdateParams.params', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\310\336\037\000\250\347\260*\001'), json_name='params', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('\202\347\260*\tauthority\212\347\260*%cosmos-sdk/x/slashing/MsgUpdateParams'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=382,
  serialized_end=581,
)


_MSGUPDATEPARAMSRESPONSE = _descriptor.Descriptor(
  name='MsgUpdateParamsResponse',
  full_name='cosmos.slashing.v1beta1.MsgUpdateParamsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=583,
  serialized_end=608,
)

_MSGUPDATEPARAMS.fields_by_name['params'].message_type = cosmos_dot_slashing_dot_v1beta1_dot_slashing__pb2._PARAMS
DESCRIPTOR.message_types_by_name['MsgUnjail'] = _MSGUNJAIL
DESCRIPTOR.message_types_by_name['MsgUnjailResponse'] = _MSGUNJAILRESPONSE
DESCRIPTOR.message_types_by_name['MsgUpdateParams'] = _MSGUPDATEPARAMS
DESCRIPTOR.message_types_by_name['MsgUpdateParamsResponse'] = _MSGUPDATEPARAMSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MsgUnjail = _reflection.GeneratedProtocolMessageType('MsgUnjail', (_message.Message,), dict(
  DESCRIPTOR = _MSGUNJAIL,
  __module__ = 'cosmos.slashing.v1beta1.tx_pb2'
  # @@protoc_insertion_point(class_scope:cosmos.slashing.v1beta1.MsgUnjail)
  ))
_sym_db.RegisterMessage(MsgUnjail)

MsgUnjailResponse = _reflection.GeneratedProtocolMessageType('MsgUnjailResponse', (_message.Message,), dict(
  DESCRIPTOR = _MSGUNJAILRESPONSE,
  __module__ = 'cosmos.slashing.v1beta1.tx_pb2'
  # @@protoc_insertion_point(class_scope:cosmos.slashing.v1beta1.MsgUnjailResponse)
  ))
_sym_db.RegisterMessage(MsgUnjailResponse)

MsgUpdateParams = _reflection.GeneratedProtocolMessageType('MsgUpdateParams', (_message.Message,), dict(
  DESCRIPTOR = _MSGUPDATEPARAMS,
  __module__ = 'cosmos.slashing.v1beta1.tx_pb2'
  # @@protoc_insertion_point(class_scope:cosmos.slashing.v1beta1.MsgUpdateParams)
  ))
_sym_db.RegisterMessage(MsgUpdateParams)

MsgUpdateParamsResponse = _reflection.GeneratedProtocolMessageType('MsgUpdateParamsResponse', (_message.Message,), dict(
  DESCRIPTOR = _MSGUPDATEPARAMSRESPONSE,
  __module__ = 'cosmos.slashing.v1beta1.tx_pb2'
  # @@protoc_insertion_point(class_scope:cosmos.slashing.v1beta1.MsgUpdateParamsResponse)
  ))
_sym_db.RegisterMessage(MsgUpdateParamsResponse)


DESCRIPTOR._options = None
_MSGUNJAIL.fields_by_name['validator_addr']._options = None
_MSGUNJAIL._options = None
_MSGUPDATEPARAMS.fields_by_name['authority']._options = None
_MSGUPDATEPARAMS.fields_by_name['params']._options = None
_MSGUPDATEPARAMS._options = None

_MSG = _descriptor.ServiceDescriptor(
  name='Msg',
  full_name='cosmos.slashing.v1beta1.Msg',
  file=DESCRIPTOR,
  index=0,
  serialized_options=_b('\200\347\260*\001'),
  serialized_start=611,
  serialized_end=821,
  methods=[
  _descriptor.MethodDescriptor(
    name='Unjail',
    full_name='cosmos.slashing.v1beta1.Msg.Unjail',
    index=0,
    containing_service=None,
    input_type=_MSGUNJAIL,
    output_type=_MSGUNJAILRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateParams',
    full_name='cosmos.slashing.v1beta1.Msg.UpdateParams',
    index=1,
    containing_service=None,
    input_type=_MSGUPDATEPARAMS,
    output_type=_MSGUPDATEPARAMSRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MSG)

DESCRIPTOR.services_by_name['Msg'] = _MSG

# @@protoc_insertion_point(module_scope)
