# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/crypto/multisig/keys.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from amino import amino_pb2 as amino_dot_amino__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cosmos/crypto/multisig/keys.proto',
  package='cosmos.crypto.multisig',
  syntax='proto3',
  serialized_options=_b('Z1github.com/cosmos/cosmos-sdk/crypto/keys/multisig'),
  serialized_pb=_b('\n!cosmos/crypto/multisig/keys.proto\x12\x16\x63osmos.crypto.multisig\x1a\x14gogoproto/gogo.proto\x1a\x19google/protobuf/any.proto\x1a\x11\x61mino/amino.proto\"\xc3\x01\n\x11LegacyAminoPubKey\x12\x1c\n\tthreshold\x18\x01 \x01(\rR\tthreshold\x12N\n\x0bpublic_keys\x18\x02 \x03(\x0b\x32\x14.google.protobuf.AnyB\x17\xe2\xde\x1f\x07PubKeys\xa2\xe7\xb0*\x07pubkeysR\npublicKeys:@\x88\xa0\x1f\x00\x8a\xe7\xb0*\"tendermint/PubKeyMultisigThreshold\x92\xe7\xb0*\x10threshold_stringB3Z1github.com/cosmos/cosmos-sdk/crypto/keys/multisigb\x06proto3')
  ,
  dependencies=[gogoproto_dot_gogo__pb2.DESCRIPTOR,google_dot_protobuf_dot_any__pb2.DESCRIPTOR,amino_dot_amino__pb2.DESCRIPTOR,])




_LEGACYAMINOPUBKEY = _descriptor.Descriptor(
  name='LegacyAminoPubKey',
  full_name='cosmos.crypto.multisig.LegacyAminoPubKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='threshold', full_name='cosmos.crypto.multisig.LegacyAminoPubKey.threshold', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='threshold', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='public_keys', full_name='cosmos.crypto.multisig.LegacyAminoPubKey.public_keys', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\342\336\037\007PubKeys\242\347\260*\007pubkeys'), json_name='publicKeys', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('\210\240\037\000\212\347\260*\"tendermint/PubKeyMultisigThreshold\222\347\260*\020threshold_string'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=325,
)

_LEGACYAMINOPUBKEY.fields_by_name['public_keys'].message_type = google_dot_protobuf_dot_any__pb2._ANY
DESCRIPTOR.message_types_by_name['LegacyAminoPubKey'] = _LEGACYAMINOPUBKEY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LegacyAminoPubKey = _reflection.GeneratedProtocolMessageType('LegacyAminoPubKey', (_message.Message,), dict(
  DESCRIPTOR = _LEGACYAMINOPUBKEY,
  __module__ = 'cosmos.crypto.multisig.keys_pb2'
  # @@protoc_insertion_point(class_scope:cosmos.crypto.multisig.LegacyAminoPubKey)
  ))
_sym_db.RegisterMessage(LegacyAminoPubKey)


DESCRIPTOR._options = None
_LEGACYAMINOPUBKEY.fields_by_name['public_keys']._options = None
_LEGACYAMINOPUBKEY._options = None
# @@protoc_insertion_point(module_scope)
