# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/orm/v1alpha1/schema.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cosmos/orm/v1alpha1/schema.proto',
  package='cosmos.orm.v1alpha1',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n cosmos/orm/v1alpha1/schema.proto\x12\x13\x63osmos.orm.v1alpha1\x1a google/protobuf/descriptor.proto\"\x93\x02\n\x16ModuleSchemaDescriptor\x12V\n\x0bschema_file\x18\x01 \x03(\x0b\x32\x35.cosmos.orm.v1alpha1.ModuleSchemaDescriptor.FileEntryR\nschemaFile\x12\x16\n\x06prefix\x18\x02 \x01(\x0cR\x06prefix\x1a\x88\x01\n\tFileEntry\x12\x0e\n\x02id\x18\x01 \x01(\rR\x02id\x12&\n\x0fproto_file_name\x18\x02 \x01(\tR\rprotoFileName\x12\x43\n\x0cstorage_type\x18\x03 \x01(\x0e\x32 .cosmos.orm.v1alpha1.StorageTypeR\x0bstorageType*h\n\x0bStorageType\x12$\n STORAGE_TYPE_DEFAULT_UNSPECIFIED\x10\x00\x12\x17\n\x13STORAGE_TYPE_MEMORY\x10\x01\x12\x1a\n\x16STORAGE_TYPE_TRANSIENT\x10\x02:t\n\rmodule_schema\x12\x1f.google.protobuf.MessageOptions\x18\xf0\xb3\xea\x31 \x01(\x0b\x32+.cosmos.orm.v1alpha1.ModuleSchemaDescriptorR\x0cmoduleSchemab\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,])

_STORAGETYPE = _descriptor.EnumDescriptor(
  name='StorageType',
  full_name='cosmos.orm.v1alpha1.StorageType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STORAGE_TYPE_DEFAULT_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STORAGE_TYPE_MEMORY', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STORAGE_TYPE_TRANSIENT', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=369,
  serialized_end=473,
)
_sym_db.RegisterEnumDescriptor(_STORAGETYPE)

StorageType = enum_type_wrapper.EnumTypeWrapper(_STORAGETYPE)
STORAGE_TYPE_DEFAULT_UNSPECIFIED = 0
STORAGE_TYPE_MEMORY = 1
STORAGE_TYPE_TRANSIENT = 2

MODULE_SCHEMA_FIELD_NUMBER = 104503792
module_schema = _descriptor.FieldDescriptor(
  name='module_schema', full_name='cosmos.orm.v1alpha1.module_schema', index=0,
  number=104503792, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, json_name='moduleSchema', file=DESCRIPTOR)


_MODULESCHEMADESCRIPTOR_FILEENTRY = _descriptor.Descriptor(
  name='FileEntry',
  full_name='cosmos.orm.v1alpha1.ModuleSchemaDescriptor.FileEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='cosmos.orm.v1alpha1.ModuleSchemaDescriptor.FileEntry.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='id', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='proto_file_name', full_name='cosmos.orm.v1alpha1.ModuleSchemaDescriptor.FileEntry.proto_file_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='protoFileName', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='storage_type', full_name='cosmos.orm.v1alpha1.ModuleSchemaDescriptor.FileEntry.storage_type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='storageType', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=231,
  serialized_end=367,
)

_MODULESCHEMADESCRIPTOR = _descriptor.Descriptor(
  name='ModuleSchemaDescriptor',
  full_name='cosmos.orm.v1alpha1.ModuleSchemaDescriptor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='schema_file', full_name='cosmos.orm.v1alpha1.ModuleSchemaDescriptor.schema_file', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='schemaFile', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='prefix', full_name='cosmos.orm.v1alpha1.ModuleSchemaDescriptor.prefix', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='prefix', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_MODULESCHEMADESCRIPTOR_FILEENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=367,
)

_MODULESCHEMADESCRIPTOR_FILEENTRY.fields_by_name['storage_type'].enum_type = _STORAGETYPE
_MODULESCHEMADESCRIPTOR_FILEENTRY.containing_type = _MODULESCHEMADESCRIPTOR
_MODULESCHEMADESCRIPTOR.fields_by_name['schema_file'].message_type = _MODULESCHEMADESCRIPTOR_FILEENTRY
DESCRIPTOR.message_types_by_name['ModuleSchemaDescriptor'] = _MODULESCHEMADESCRIPTOR
DESCRIPTOR.enum_types_by_name['StorageType'] = _STORAGETYPE
DESCRIPTOR.extensions_by_name['module_schema'] = module_schema
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ModuleSchemaDescriptor = _reflection.GeneratedProtocolMessageType('ModuleSchemaDescriptor', (_message.Message,), dict(

  FileEntry = _reflection.GeneratedProtocolMessageType('FileEntry', (_message.Message,), dict(
    DESCRIPTOR = _MODULESCHEMADESCRIPTOR_FILEENTRY,
    __module__ = 'cosmos.orm.v1alpha1.schema_pb2'
    # @@protoc_insertion_point(class_scope:cosmos.orm.v1alpha1.ModuleSchemaDescriptor.FileEntry)
    ))
  ,
  DESCRIPTOR = _MODULESCHEMADESCRIPTOR,
  __module__ = 'cosmos.orm.v1alpha1.schema_pb2'
  # @@protoc_insertion_point(class_scope:cosmos.orm.v1alpha1.ModuleSchemaDescriptor)
  ))
_sym_db.RegisterMessage(ModuleSchemaDescriptor)
_sym_db.RegisterMessage(ModuleSchemaDescriptor.FileEntry)

module_schema.message_type = _MODULESCHEMADESCRIPTOR
google_dot_protobuf_dot_descriptor__pb2.MessageOptions.RegisterExtension(module_schema)

# @@protoc_insertion_point(module_scope)
