# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: osmosis/streamswap/v1/genesis.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from cosmos_proto import cosmos_pb2 as cosmos__proto_dot_cosmos__pb2
from cosmos.base.v1beta1 import coin_pb2 as cosmos_dot_base_dot_v1beta1_dot_coin__pb2
from osmosis.streamswap.v1 import state_pb2 as osmosis_dot_streamswap_dot_v1_dot_state__pb2
from osmosis.streamswap.v1 import params_pb2 as osmosis_dot_streamswap_dot_v1_dot_params__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='osmosis/streamswap/v1/genesis.proto',
  package='osmosis.streamswap.v1',
  syntax='proto3',
  serialized_options=_b('Z6github.com/osmosis-labs/osmosis/v12/x/streamswap/types'),
  serialized_pb=_b('\n#osmosis/streamswap/v1/genesis.proto\x12\x15osmosis.streamswap.v1\x1a\x14gogoproto/gogo.proto\x1a\x19\x63osmos_proto/cosmos.proto\x1a\x1e\x63osmos/base/v1beta1/coin.proto\x1a!osmosis/streamswap/v1/state.proto\x1a\"osmosis/streamswap/v1/params.proto\"\xfa\x01\n\x0cGenesisState\x12\x37\n\x05sales\x18\x01 \x03(\x0b\x32\x1b.osmosis.streamswap.v1.SaleB\x04\xc8\xde\x1f\x00R\x05sales\x12R\n\x0euser_positions\x18\x02 \x03(\x0b\x32%.osmosis.streamswap.v1.UserPositionKVB\x04\xc8\xde\x1f\x00R\ruserPositions\x12 \n\x0cnext_sale_id\x18\x03 \x01(\x04R\nnextSaleId\x12;\n\x06params\x18\x04 \x01(\x0b\x32\x1d.osmosis.streamswap.v1.ParamsB\x04\xc8\xde\x1f\x00R\x06params\"\x9a\x01\n\x0eUserPositionKV\x12\x1f\n\x0b\x61\x63\x63_address\x18\x01 \x01(\tR\naccAddress\x12\x17\n\x07sale_id\x18\x02 \x01(\x04R\x06saleId\x12N\n\ruser_position\x18\x03 \x01(\x0b\x32#.osmosis.streamswap.v1.UserPositionB\x04\xc8\xde\x1f\x00R\x0cuserPositionB8Z6github.com/osmosis-labs/osmosis/v12/x/streamswap/typesb\x06proto3')
  ,
  dependencies=[gogoproto_dot_gogo__pb2.DESCRIPTOR,cosmos__proto_dot_cosmos__pb2.DESCRIPTOR,cosmos_dot_base_dot_v1beta1_dot_coin__pb2.DESCRIPTOR,osmosis_dot_streamswap_dot_v1_dot_state__pb2.DESCRIPTOR,osmosis_dot_streamswap_dot_v1_dot_params__pb2.DESCRIPTOR,])




_GENESISSTATE = _descriptor.Descriptor(
  name='GenesisState',
  full_name='osmosis.streamswap.v1.GenesisState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sales', full_name='osmosis.streamswap.v1.GenesisState.sales', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\310\336\037\000'), json_name='sales', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_positions', full_name='osmosis.streamswap.v1.GenesisState.user_positions', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\310\336\037\000'), json_name='userPositions', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='next_sale_id', full_name='osmosis.streamswap.v1.GenesisState.next_sale_id', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='nextSaleId', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='params', full_name='osmosis.streamswap.v1.GenesisState.params', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\310\336\037\000'), json_name='params', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=215,
  serialized_end=465,
)


_USERPOSITIONKV = _descriptor.Descriptor(
  name='UserPositionKV',
  full_name='osmosis.streamswap.v1.UserPositionKV',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='acc_address', full_name='osmosis.streamswap.v1.UserPositionKV.acc_address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='accAddress', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sale_id', full_name='osmosis.streamswap.v1.UserPositionKV.sale_id', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='saleId', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_position', full_name='osmosis.streamswap.v1.UserPositionKV.user_position', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\310\336\037\000'), json_name='userPosition', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=468,
  serialized_end=622,
)

_GENESISSTATE.fields_by_name['sales'].message_type = osmosis_dot_streamswap_dot_v1_dot_state__pb2._SALE
_GENESISSTATE.fields_by_name['user_positions'].message_type = _USERPOSITIONKV
_GENESISSTATE.fields_by_name['params'].message_type = osmosis_dot_streamswap_dot_v1_dot_params__pb2._PARAMS
_USERPOSITIONKV.fields_by_name['user_position'].message_type = osmosis_dot_streamswap_dot_v1_dot_state__pb2._USERPOSITION
DESCRIPTOR.message_types_by_name['GenesisState'] = _GENESISSTATE
DESCRIPTOR.message_types_by_name['UserPositionKV'] = _USERPOSITIONKV
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GenesisState = _reflection.GeneratedProtocolMessageType('GenesisState', (_message.Message,), dict(
  DESCRIPTOR = _GENESISSTATE,
  __module__ = 'osmosis.streamswap.v1.genesis_pb2'
  # @@protoc_insertion_point(class_scope:osmosis.streamswap.v1.GenesisState)
  ))
_sym_db.RegisterMessage(GenesisState)

UserPositionKV = _reflection.GeneratedProtocolMessageType('UserPositionKV', (_message.Message,), dict(
  DESCRIPTOR = _USERPOSITIONKV,
  __module__ = 'osmosis.streamswap.v1.genesis_pb2'
  # @@protoc_insertion_point(class_scope:osmosis.streamswap.v1.UserPositionKV)
  ))
_sym_db.RegisterMessage(UserPositionKV)


DESCRIPTOR._options = None
_GENESISSTATE.fields_by_name['sales']._options = None
_GENESISSTATE.fields_by_name['user_positions']._options = None
_GENESISSTATE.fields_by_name['params']._options = None
_USERPOSITIONKV.fields_by_name['user_position']._options = None
# @@protoc_insertion_point(module_scope)
