# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/circuit/v1/tx.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cosmos.msg.v1 import msg_pb2 as cosmos_dot_msg_dot_v1_dot_msg__pb2
from cosmos.circuit.v1 import types_pb2 as cosmos_dot_circuit_dot_v1_dot_types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cosmos/circuit/v1/tx.proto',
  package='cosmos.circuit.v1',
  syntax='proto3',
  serialized_options=_b('Z\034cosmossdk.io/x/circuit/types'),
  serialized_pb=_b('\n\x1a\x63osmos/circuit/v1/tx.proto\x12\x11\x63osmos.circuit.v1\x1a\x17\x63osmos/msg/v1/msg.proto\x1a\x1d\x63osmos/circuit/v1/types.proto\"\xa0\x01\n\x1aMsgAuthorizeCircuitBreaker\x12\x18\n\x07granter\x18\x01 \x01(\tR\x07granter\x12\x18\n\x07grantee\x18\x02 \x01(\tR\x07grantee\x12@\n\x0bpermissions\x18\x03 \x01(\x0b\x32\x1e.cosmos.circuit.v1.PermissionsR\x0bpermissions:\x0c\x82\xe7\xb0*\x07granter\">\n\"MsgAuthorizeCircuitBreakerResponse\x12\x18\n\x07success\x18\x01 \x01(\x08R\x07success\"i\n\x15MsgTripCircuitBreaker\x12\x1c\n\tauthority\x18\x01 \x01(\tR\tauthority\x12\"\n\rmsg_type_urls\x18\x02 \x03(\tR\x0bmsgTypeUrls:\x0e\x82\xe7\xb0*\tauthority\"9\n\x1dMsgTripCircuitBreakerResponse\x12\x18\n\x07success\x18\x01 \x01(\x08R\x07success\"j\n\x16MsgResetCircuitBreaker\x12\x1c\n\tauthority\x18\x01 \x01(\tR\tauthority\x12\"\n\rmsg_type_urls\x18\x03 \x03(\tR\x0bmsgTypeUrls:\x0e\x82\xe7\xb0*\tauthority\":\n\x1eMsgResetCircuitBreakerResponse\x12\x18\n\x07success\x18\x01 \x01(\x08R\x07success2\xf4\x02\n\x03Msg\x12\x7f\n\x17\x41uthorizeCircuitBreaker\x12-.cosmos.circuit.v1.MsgAuthorizeCircuitBreaker\x1a\x35.cosmos.circuit.v1.MsgAuthorizeCircuitBreakerResponse\x12p\n\x12TripCircuitBreaker\x12(.cosmos.circuit.v1.MsgTripCircuitBreaker\x1a\x30.cosmos.circuit.v1.MsgTripCircuitBreakerResponse\x12s\n\x13ResetCircuitBreaker\x12).cosmos.circuit.v1.MsgResetCircuitBreaker\x1a\x31.cosmos.circuit.v1.MsgResetCircuitBreakerResponse\x1a\x05\x80\xe7\xb0*\x01\x42\x1eZ\x1c\x63osmossdk.io/x/circuit/typesb\x06proto3')
  ,
  dependencies=[cosmos_dot_msg_dot_v1_dot_msg__pb2.DESCRIPTOR,cosmos_dot_circuit_dot_v1_dot_types__pb2.DESCRIPTOR,])




_MSGAUTHORIZECIRCUITBREAKER = _descriptor.Descriptor(
  name='MsgAuthorizeCircuitBreaker',
  full_name='cosmos.circuit.v1.MsgAuthorizeCircuitBreaker',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='granter', full_name='cosmos.circuit.v1.MsgAuthorizeCircuitBreaker.granter', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='granter', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='grantee', full_name='cosmos.circuit.v1.MsgAuthorizeCircuitBreaker.grantee', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='grantee', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='permissions', full_name='cosmos.circuit.v1.MsgAuthorizeCircuitBreaker.permissions', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='permissions', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('\202\347\260*\007granter'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=266,
)


_MSGAUTHORIZECIRCUITBREAKERRESPONSE = _descriptor.Descriptor(
  name='MsgAuthorizeCircuitBreakerResponse',
  full_name='cosmos.circuit.v1.MsgAuthorizeCircuitBreakerResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='cosmos.circuit.v1.MsgAuthorizeCircuitBreakerResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='success', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=268,
  serialized_end=330,
)


_MSGTRIPCIRCUITBREAKER = _descriptor.Descriptor(
  name='MsgTripCircuitBreaker',
  full_name='cosmos.circuit.v1.MsgTripCircuitBreaker',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='authority', full_name='cosmos.circuit.v1.MsgTripCircuitBreaker.authority', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='authority', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg_type_urls', full_name='cosmos.circuit.v1.MsgTripCircuitBreaker.msg_type_urls', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='msgTypeUrls', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('\202\347\260*\tauthority'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=332,
  serialized_end=437,
)


_MSGTRIPCIRCUITBREAKERRESPONSE = _descriptor.Descriptor(
  name='MsgTripCircuitBreakerResponse',
  full_name='cosmos.circuit.v1.MsgTripCircuitBreakerResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='cosmos.circuit.v1.MsgTripCircuitBreakerResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='success', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=439,
  serialized_end=496,
)


_MSGRESETCIRCUITBREAKER = _descriptor.Descriptor(
  name='MsgResetCircuitBreaker',
  full_name='cosmos.circuit.v1.MsgResetCircuitBreaker',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='authority', full_name='cosmos.circuit.v1.MsgResetCircuitBreaker.authority', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='authority', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg_type_urls', full_name='cosmos.circuit.v1.MsgResetCircuitBreaker.msg_type_urls', index=1,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='msgTypeUrls', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('\202\347\260*\tauthority'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=498,
  serialized_end=604,
)


_MSGRESETCIRCUITBREAKERRESPONSE = _descriptor.Descriptor(
  name='MsgResetCircuitBreakerResponse',
  full_name='cosmos.circuit.v1.MsgResetCircuitBreakerResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='cosmos.circuit.v1.MsgResetCircuitBreakerResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='success', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=606,
  serialized_end=664,
)

_MSGAUTHORIZECIRCUITBREAKER.fields_by_name['permissions'].message_type = cosmos_dot_circuit_dot_v1_dot_types__pb2._PERMISSIONS
DESCRIPTOR.message_types_by_name['MsgAuthorizeCircuitBreaker'] = _MSGAUTHORIZECIRCUITBREAKER
DESCRIPTOR.message_types_by_name['MsgAuthorizeCircuitBreakerResponse'] = _MSGAUTHORIZECIRCUITBREAKERRESPONSE
DESCRIPTOR.message_types_by_name['MsgTripCircuitBreaker'] = _MSGTRIPCIRCUITBREAKER
DESCRIPTOR.message_types_by_name['MsgTripCircuitBreakerResponse'] = _MSGTRIPCIRCUITBREAKERRESPONSE
DESCRIPTOR.message_types_by_name['MsgResetCircuitBreaker'] = _MSGRESETCIRCUITBREAKER
DESCRIPTOR.message_types_by_name['MsgResetCircuitBreakerResponse'] = _MSGRESETCIRCUITBREAKERRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MsgAuthorizeCircuitBreaker = _reflection.GeneratedProtocolMessageType('MsgAuthorizeCircuitBreaker', (_message.Message,), dict(
  DESCRIPTOR = _MSGAUTHORIZECIRCUITBREAKER,
  __module__ = 'cosmos.circuit.v1.tx_pb2'
  # @@protoc_insertion_point(class_scope:cosmos.circuit.v1.MsgAuthorizeCircuitBreaker)
  ))
_sym_db.RegisterMessage(MsgAuthorizeCircuitBreaker)

MsgAuthorizeCircuitBreakerResponse = _reflection.GeneratedProtocolMessageType('MsgAuthorizeCircuitBreakerResponse', (_message.Message,), dict(
  DESCRIPTOR = _MSGAUTHORIZECIRCUITBREAKERRESPONSE,
  __module__ = 'cosmos.circuit.v1.tx_pb2'
  # @@protoc_insertion_point(class_scope:cosmos.circuit.v1.MsgAuthorizeCircuitBreakerResponse)
  ))
_sym_db.RegisterMessage(MsgAuthorizeCircuitBreakerResponse)

MsgTripCircuitBreaker = _reflection.GeneratedProtocolMessageType('MsgTripCircuitBreaker', (_message.Message,), dict(
  DESCRIPTOR = _MSGTRIPCIRCUITBREAKER,
  __module__ = 'cosmos.circuit.v1.tx_pb2'
  # @@protoc_insertion_point(class_scope:cosmos.circuit.v1.MsgTripCircuitBreaker)
  ))
_sym_db.RegisterMessage(MsgTripCircuitBreaker)

MsgTripCircuitBreakerResponse = _reflection.GeneratedProtocolMessageType('MsgTripCircuitBreakerResponse', (_message.Message,), dict(
  DESCRIPTOR = _MSGTRIPCIRCUITBREAKERRESPONSE,
  __module__ = 'cosmos.circuit.v1.tx_pb2'
  # @@protoc_insertion_point(class_scope:cosmos.circuit.v1.MsgTripCircuitBreakerResponse)
  ))
_sym_db.RegisterMessage(MsgTripCircuitBreakerResponse)

MsgResetCircuitBreaker = _reflection.GeneratedProtocolMessageType('MsgResetCircuitBreaker', (_message.Message,), dict(
  DESCRIPTOR = _MSGRESETCIRCUITBREAKER,
  __module__ = 'cosmos.circuit.v1.tx_pb2'
  # @@protoc_insertion_point(class_scope:cosmos.circuit.v1.MsgResetCircuitBreaker)
  ))
_sym_db.RegisterMessage(MsgResetCircuitBreaker)

MsgResetCircuitBreakerResponse = _reflection.GeneratedProtocolMessageType('MsgResetCircuitBreakerResponse', (_message.Message,), dict(
  DESCRIPTOR = _MSGRESETCIRCUITBREAKERRESPONSE,
  __module__ = 'cosmos.circuit.v1.tx_pb2'
  # @@protoc_insertion_point(class_scope:cosmos.circuit.v1.MsgResetCircuitBreakerResponse)
  ))
_sym_db.RegisterMessage(MsgResetCircuitBreakerResponse)


DESCRIPTOR._options = None
_MSGAUTHORIZECIRCUITBREAKER._options = None
_MSGTRIPCIRCUITBREAKER._options = None
_MSGRESETCIRCUITBREAKER._options = None

_MSG = _descriptor.ServiceDescriptor(
  name='Msg',
  full_name='cosmos.circuit.v1.Msg',
  file=DESCRIPTOR,
  index=0,
  serialized_options=_b('\200\347\260*\001'),
  serialized_start=667,
  serialized_end=1039,
  methods=[
  _descriptor.MethodDescriptor(
    name='AuthorizeCircuitBreaker',
    full_name='cosmos.circuit.v1.Msg.AuthorizeCircuitBreaker',
    index=0,
    containing_service=None,
    input_type=_MSGAUTHORIZECIRCUITBREAKER,
    output_type=_MSGAUTHORIZECIRCUITBREAKERRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='TripCircuitBreaker',
    full_name='cosmos.circuit.v1.Msg.TripCircuitBreaker',
    index=1,
    containing_service=None,
    input_type=_MSGTRIPCIRCUITBREAKER,
    output_type=_MSGTRIPCIRCUITBREAKERRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ResetCircuitBreaker',
    full_name='cosmos.circuit.v1.Msg.ResetCircuitBreaker',
    index=2,
    containing_service=None,
    input_type=_MSGRESETCIRCUITBREAKER,
    output_type=_MSGRESETCIRCUITBREAKERRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MSG)

DESCRIPTOR.services_by_name['Msg'] = _MSG

# @@protoc_insertion_point(module_scope)
