# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: osmosis/twap/v1beta1/genesis.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from osmosis.twap.v1beta1 import twap_record_pb2 as osmosis_dot_twap_dot_v1beta1_dot_twap__record__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from cosmos_proto import cosmos_pb2 as cosmos__proto_dot_cosmos__pb2
from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='osmosis/twap/v1beta1/genesis.proto',
  package='osmosis.twap.v1beta1',
  syntax='proto3',
  serialized_options=_b('Z0github.com/osmosis-labs/osmosis/v12/x/twap/types'),
  serialized_pb=_b('\n\"osmosis/twap/v1beta1/genesis.proto\x12\x14osmosis.twap.v1beta1\x1a\x14gogoproto/gogo.proto\x1a&osmosis/twap/v1beta1/twap_record.proto\x1a\x19google/protobuf/any.proto\x1a\x19\x63osmos_proto/cosmos.proto\x1a\x1egoogle/protobuf/duration.proto\"\xc6\x01\n\x06Params\x12\x34\n\x16prune_epoch_identifier\x18\x01 \x01(\tR\x14pruneEpochIdentifier\x12\x85\x01\n\x1arecord_history_keep_period\x18\x02 \x01(\x0b\x32\x19.google.protobuf.DurationB-\xc8\xde\x1f\x00\xf2\xde\x1f!yaml:\"record_history_keep_period\"\x98\xdf\x1f\x01R\x17recordHistoryKeepPeriod\"\x88\x01\n\x0cGenesisState\x12<\n\x05twaps\x18\x01 \x03(\x0b\x32 .osmosis.twap.v1beta1.TwapRecordB\x04\xc8\xde\x1f\x00R\x05twaps\x12:\n\x06params\x18\x02 \x01(\x0b\x32\x1c.osmosis.twap.v1beta1.ParamsB\x04\xc8\xde\x1f\x00R\x06paramsB2Z0github.com/osmosis-labs/osmosis/v12/x/twap/typesb\x06proto3')
  ,
  dependencies=[gogoproto_dot_gogo__pb2.DESCRIPTOR,osmosis_dot_twap_dot_v1beta1_dot_twap__record__pb2.DESCRIPTOR,google_dot_protobuf_dot_any__pb2.DESCRIPTOR,cosmos__proto_dot_cosmos__pb2.DESCRIPTOR,google_dot_protobuf_dot_duration__pb2.DESCRIPTOR,])




_PARAMS = _descriptor.Descriptor(
  name='Params',
  full_name='osmosis.twap.v1beta1.Params',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='prune_epoch_identifier', full_name='osmosis.twap.v1beta1.Params.prune_epoch_identifier', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='pruneEpochIdentifier', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='record_history_keep_period', full_name='osmosis.twap.v1beta1.Params.record_history_keep_period', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\310\336\037\000\362\336\037!yaml:\"record_history_keep_period\"\230\337\037\001'), json_name='recordHistoryKeepPeriod', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=209,
  serialized_end=407,
)


_GENESISSTATE = _descriptor.Descriptor(
  name='GenesisState',
  full_name='osmosis.twap.v1beta1.GenesisState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='twaps', full_name='osmosis.twap.v1beta1.GenesisState.twaps', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\310\336\037\000'), json_name='twaps', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='params', full_name='osmosis.twap.v1beta1.GenesisState.params', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\310\336\037\000'), json_name='params', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=410,
  serialized_end=546,
)

_PARAMS.fields_by_name['record_history_keep_period'].message_type = google_dot_protobuf_dot_duration__pb2._DURATION
_GENESISSTATE.fields_by_name['twaps'].message_type = osmosis_dot_twap_dot_v1beta1_dot_twap__record__pb2._TWAPRECORD
_GENESISSTATE.fields_by_name['params'].message_type = _PARAMS
DESCRIPTOR.message_types_by_name['Params'] = _PARAMS
DESCRIPTOR.message_types_by_name['GenesisState'] = _GENESISSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Params = _reflection.GeneratedProtocolMessageType('Params', (_message.Message,), dict(
  DESCRIPTOR = _PARAMS,
  __module__ = 'osmosis.twap.v1beta1.genesis_pb2'
  # @@protoc_insertion_point(class_scope:osmosis.twap.v1beta1.Params)
  ))
_sym_db.RegisterMessage(Params)

GenesisState = _reflection.GeneratedProtocolMessageType('GenesisState', (_message.Message,), dict(
  DESCRIPTOR = _GENESISSTATE,
  __module__ = 'osmosis.twap.v1beta1.genesis_pb2'
  # @@protoc_insertion_point(class_scope:osmosis.twap.v1beta1.GenesisState)
  ))
_sym_db.RegisterMessage(GenesisState)


DESCRIPTOR._options = None
_PARAMS.fields_by_name['record_history_keep_period']._options = None
_GENESISSTATE.fields_by_name['twaps']._options = None
_GENESISSTATE.fields_by_name['params']._options = None
# @@protoc_insertion_point(module_scope)
