# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/autocli/v1/query.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cosmos.autocli.v1 import options_pb2 as cosmos_dot_autocli_dot_v1_dot_options__pb2
from cosmos.query.v1 import query_pb2 as cosmos_dot_query_dot_v1_dot_query__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cosmos/autocli/v1/query.proto',
  package='cosmos.autocli.v1',
  syntax='proto3',
  serialized_options=_b('Z)cosmossdk.io/api/cosmos/base/cli/v1;cliv1'),
  serialized_pb=_b('\n\x1d\x63osmos/autocli/v1/query.proto\x12\x11\x63osmos.autocli.v1\x1a\x1f\x63osmos/autocli/v1/options.proto\x1a\x1b\x63osmos/query/v1/query.proto\"\x13\n\x11\x41ppOptionsRequest\"\xd9\x01\n\x12\x41ppOptionsResponse\x12_\n\x0emodule_options\x18\x01 \x03(\x0b\x32\x38.cosmos.autocli.v1.AppOptionsResponse.ModuleOptionsEntryR\rmoduleOptions\x1a\x62\n\x12ModuleOptionsEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x36\n\x05value\x18\x02 \x01(\x0b\x32 .cosmos.autocli.v1.ModuleOptionsR\x05value:\x02\x38\x01\x32i\n\x05Query\x12`\n\nAppOptions\x12$.cosmos.autocli.v1.AppOptionsRequest\x1a%.cosmos.autocli.v1.AppOptionsResponse\"\x05\x88\xe7\xb0*\x00\x42+Z)cosmossdk.io/api/cosmos/base/cli/v1;cliv1b\x06proto3')
  ,
  dependencies=[cosmos_dot_autocli_dot_v1_dot_options__pb2.DESCRIPTOR,cosmos_dot_query_dot_v1_dot_query__pb2.DESCRIPTOR,])




_APPOPTIONSREQUEST = _descriptor.Descriptor(
  name='AppOptionsRequest',
  full_name='cosmos.autocli.v1.AppOptionsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=133,
)


_APPOPTIONSRESPONSE_MODULEOPTIONSENTRY = _descriptor.Descriptor(
  name='ModuleOptionsEntry',
  full_name='cosmos.autocli.v1.AppOptionsResponse.ModuleOptionsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='cosmos.autocli.v1.AppOptionsResponse.ModuleOptionsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='key', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='cosmos.autocli.v1.AppOptionsResponse.ModuleOptionsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='value', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=255,
  serialized_end=353,
)

_APPOPTIONSRESPONSE = _descriptor.Descriptor(
  name='AppOptionsResponse',
  full_name='cosmos.autocli.v1.AppOptionsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='module_options', full_name='cosmos.autocli.v1.AppOptionsResponse.module_options', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='moduleOptions', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_APPOPTIONSRESPONSE_MODULEOPTIONSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=353,
)

_APPOPTIONSRESPONSE_MODULEOPTIONSENTRY.fields_by_name['value'].message_type = cosmos_dot_autocli_dot_v1_dot_options__pb2._MODULEOPTIONS
_APPOPTIONSRESPONSE_MODULEOPTIONSENTRY.containing_type = _APPOPTIONSRESPONSE
_APPOPTIONSRESPONSE.fields_by_name['module_options'].message_type = _APPOPTIONSRESPONSE_MODULEOPTIONSENTRY
DESCRIPTOR.message_types_by_name['AppOptionsRequest'] = _APPOPTIONSREQUEST
DESCRIPTOR.message_types_by_name['AppOptionsResponse'] = _APPOPTIONSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AppOptionsRequest = _reflection.GeneratedProtocolMessageType('AppOptionsRequest', (_message.Message,), dict(
  DESCRIPTOR = _APPOPTIONSREQUEST,
  __module__ = 'cosmos.autocli.v1.query_pb2'
  # @@protoc_insertion_point(class_scope:cosmos.autocli.v1.AppOptionsRequest)
  ))
_sym_db.RegisterMessage(AppOptionsRequest)

AppOptionsResponse = _reflection.GeneratedProtocolMessageType('AppOptionsResponse', (_message.Message,), dict(

  ModuleOptionsEntry = _reflection.GeneratedProtocolMessageType('ModuleOptionsEntry', (_message.Message,), dict(
    DESCRIPTOR = _APPOPTIONSRESPONSE_MODULEOPTIONSENTRY,
    __module__ = 'cosmos.autocli.v1.query_pb2'
    # @@protoc_insertion_point(class_scope:cosmos.autocli.v1.AppOptionsResponse.ModuleOptionsEntry)
    ))
  ,
  DESCRIPTOR = _APPOPTIONSRESPONSE,
  __module__ = 'cosmos.autocli.v1.query_pb2'
  # @@protoc_insertion_point(class_scope:cosmos.autocli.v1.AppOptionsResponse)
  ))
_sym_db.RegisterMessage(AppOptionsResponse)
_sym_db.RegisterMessage(AppOptionsResponse.ModuleOptionsEntry)


DESCRIPTOR._options = None
_APPOPTIONSRESPONSE_MODULEOPTIONSENTRY._options = None

_QUERY = _descriptor.ServiceDescriptor(
  name='Query',
  full_name='cosmos.autocli.v1.Query',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=355,
  serialized_end=460,
  methods=[
  _descriptor.MethodDescriptor(
    name='AppOptions',
    full_name='cosmos.autocli.v1.Query.AppOptions',
    index=0,
    containing_service=None,
    input_type=_APPOPTIONSREQUEST,
    output_type=_APPOPTIONSRESPONSE,
    serialized_options=_b('\210\347\260*\000'),
  ),
])
_sym_db.RegisterServiceDescriptor(_QUERY)

DESCRIPTOR.services_by_name['Query'] = _QUERY

# @@protoc_insertion_point(module_scope)
