# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: osmosis/tokenfactory/v1beta1/authorityMetadata.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from cosmos.base.v1beta1 import coin_pb2 as cosmos_dot_base_dot_v1beta1_dot_coin__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='osmosis/tokenfactory/v1beta1/authorityMetadata.proto',
  package='osmosis.tokenfactory.v1beta1',
  syntax='proto3',
  serialized_options=_b('Z8github.com/osmosis-labs/osmosis/v12/x/tokenfactory/types'),
  serialized_pb=_b('\n4osmosis/tokenfactory/v1beta1/authorityMetadata.proto\x12\x1cosmosis.tokenfactory.v1beta1\x1a\x14gogoproto/gogo.proto\x1a\x1e\x63osmos/base/v1beta1/coin.proto\"F\n\x16\x44\x65nomAuthorityMetadata\x12&\n\x05\x61\x64min\x18\x01 \x01(\tB\x10\xf2\xde\x1f\x0cyaml:\"admin\"R\x05\x61\x64min:\x04\xe8\xa0\x1f\x01\x42:Z8github.com/osmosis-labs/osmosis/v12/x/tokenfactory/typesb\x06proto3')
  ,
  dependencies=[gogoproto_dot_gogo__pb2.DESCRIPTOR,cosmos_dot_base_dot_v1beta1_dot_coin__pb2.DESCRIPTOR,])




_DENOMAUTHORITYMETADATA = _descriptor.Descriptor(
  name='DenomAuthorityMetadata',
  full_name='osmosis.tokenfactory.v1beta1.DenomAuthorityMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='admin', full_name='osmosis.tokenfactory.v1beta1.DenomAuthorityMetadata.admin', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\362\336\037\014yaml:\"admin\"'), json_name='admin', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('\350\240\037\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=210,
)

DESCRIPTOR.message_types_by_name['DenomAuthorityMetadata'] = _DENOMAUTHORITYMETADATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DenomAuthorityMetadata = _reflection.GeneratedProtocolMessageType('DenomAuthorityMetadata', (_message.Message,), dict(
  DESCRIPTOR = _DENOMAUTHORITYMETADATA,
  __module__ = 'osmosis.tokenfactory.v1beta1.authorityMetadata_pb2'
  # @@protoc_insertion_point(class_scope:osmosis.tokenfactory.v1beta1.DenomAuthorityMetadata)
  ))
_sym_db.RegisterMessage(DenomAuthorityMetadata)


DESCRIPTOR._options = None
_DENOMAUTHORITYMETADATA.fields_by_name['admin']._options = None
_DENOMAUTHORITYMETADATA._options = None
# @@protoc_insertion_point(module_scope)
